# -*- coding: utf-8 -*-
"""Simple Biodata Program.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TODTtUzxO7tqTRWbMUwHroFNCmDNvZ0j
"""

Name="Sanja"
Gender="Female"
Province="East Java"
Hobby="Watching dramas and playing games"
Dream_career="Data Scientist"

print("Name         :", Name)
print("Gender       :", Gender)
print("Province     :", Province)
print("Hobby        :", Hobby)
print("Dream career :", Dream_career)